Traceback (most recent call last):
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 160, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 648, in async_setup_kernel
    yield
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bsipocz/.pyenv/versions/3.11.0/lib/python3.11/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
parquet_loadname = 'output/df_lc_5k.parquet.gzip'
parallel_df_lc = MultiIndexDFObject()
parallel_df_lc.data = pd.read_parquet(parquet_loadname)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn [2], line 3[0m
[1;32m      1[0m parquet_loadname [38;5;241m=[39m [38;5;124m'[39m[38;5;124moutput/df_lc_5k.parquet.gzip[39m[38;5;124m'[39m
[1;32m      2[0m parallel_df_lc [38;5;241m=[39m MultiIndexDFObject()
[0;32m----> 3[0m parallel_df_lc[38;5;241m.[39mdata [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_parquet[49m[43m([49m[43mparquet_loadname[49m[43m)[49m

File [0;32m~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pandas/io/parquet.py:670[0m, in [0;36mread_parquet[0;34m(path, engine, columns, storage_options, use_nullable_dtypes, dtype_backend, filesystem, filters, **kwargs)[0m
[1;32m    667[0m     use_nullable_dtypes [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    668[0m check_dtype_backend(dtype_backend)
[0;32m--> 670[0m [38;5;28;01mreturn[39;00m [43mimpl[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m
[1;32m    671[0m [43m    [49m[43mpath[49m[43m,[49m
[1;32m    672[0m [43m    [49m[43mcolumns[49m[38;5;241;43m=[39;49m[43mcolumns[49m[43m,[49m
[1;32m    673[0m [43m    [49m[43mfilters[49m[38;5;241;43m=[39;49m[43mfilters[49m[43m,[49m
[1;32m    674[0m [43m    [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m
[1;32m    675[0m [43m    [49m[43muse_nullable_dtypes[49m[38;5;241;43m=[39;49m[43muse_nullable_dtypes[49m[43m,[49m
[1;32m    676[0m [43m    [49m[43mdtype_backend[49m[38;5;241;43m=[39;49m[43mdtype_backend[49m[43m,[49m
[1;32m    677[0m [43m    [49m[43mfilesystem[49m[38;5;241;43m=[39;49m[43mfilesystem[49m[43m,[49m
[1;32m    678[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m    679[0m [43m[49m[43m)[49m

File [0;32m~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pandas/io/parquet.py:265[0m, in [0;36mPyArrowImpl.read[0;34m(self, path, columns, filters, use_nullable_dtypes, dtype_backend, storage_options, filesystem, **kwargs)[0m
[1;32m    262[0m [38;5;28;01mif[39;00m manager [38;5;241m==[39m [38;5;124m"[39m[38;5;124marray[39m[38;5;124m"[39m:
[1;32m    263[0m     to_pandas_kwargs[[38;5;124m"[39m[38;5;124msplit_blocks[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28;01mTrue[39;00m  [38;5;66;03m# type: ignore[assignment][39;00m
[0;32m--> 265[0m path_or_handle, handles, filesystem [38;5;241m=[39m [43m_get_path_or_handle[49m[43m([49m
[1;32m    266[0m [43m    [49m[43mpath[49m[43m,[49m
[1;32m    267[0m [43m    [49m[43mfilesystem[49m[43m,[49m
[1;32m    268[0m [43m    [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m
[1;32m    269[0m [43m    [49m[43mmode[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m    270[0m [43m[49m[43m)[49m
[1;32m    271[0m [38;5;28;01mtry[39;00m:
[1;32m    272[0m     pa_table [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mapi[38;5;241m.[39mparquet[38;5;241m.[39mread_table(
[1;32m    273[0m         path_or_handle,
[1;32m    274[0m         columns[38;5;241m=[39mcolumns,
[0;32m   (...)[0m
[1;32m    277[0m         [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m    278[0m     )

File [0;32m~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pandas/io/parquet.py:139[0m, in [0;36m_get_path_or_handle[0;34m(path, fs, storage_options, mode, is_dir)[0m
[1;32m    129[0m handles [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    130[0m [38;5;28;01mif[39;00m (
[1;32m    131[0m     [38;5;129;01mnot[39;00m fs
[1;32m    132[0m     [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m is_dir
[0;32m   (...)[0m
[1;32m    137[0m     [38;5;66;03m# fsspec resources can also point to directories[39;00m
[1;32m    138[0m     [38;5;66;03m# this branch is used for example when reading from non-fsspec URLs[39;00m
[0;32m--> 139[0m     handles [38;5;241m=[39m [43mget_handle[49m[43m([49m
[1;32m    140[0m [43m        [49m[43mpath_or_handle[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43mis_text[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m
[1;32m    141[0m [43m    [49m[43m)[49m
[1;32m    142[0m     fs [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    143[0m     path_or_handle [38;5;241m=[39m handles[38;5;241m.[39mhandle

File [0;32m~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pandas/io/common.py:872[0m, in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    863[0m         handle [38;5;241m=[39m [38;5;28mopen[39m(
[1;32m    864[0m             handle,
[1;32m    865[0m             ioargs[38;5;241m.[39mmode,
[0;32m   (...)[0m
[1;32m    868[0m             newline[38;5;241m=[39m[38;5;124m"[39m[38;5;124m"[39m,
[1;32m    869[0m         )
[1;32m    870[0m     [38;5;28;01melse[39;00m:
[1;32m    871[0m         [38;5;66;03m# Binary mode[39;00m
[0;32m--> 872[0m         handle [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mhandle[49m[43m,[49m[43m [49m[43mioargs[49m[38;5;241;43m.[39;49m[43mmode[49m[43m)[49m
[1;32m    873[0m     handles[38;5;241m.[39mappend(handle)
[1;32m    875[0m [38;5;66;03m# Convert BytesIO or file objects passed with an encoding[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'output/df_lc_5k.parquet.gzip'
FileNotFoundError: [Errno 2] No such file or directory: 'output/df_lc_5k.parquet.gzip'

